### ISSUE TITLE
Trying holmesgpt with local ollama3.1 fails w. KeyError: 'name'

### ISSUE THREAD

**Issue by suukit** [robusta-dev/holmesgpt#129]
Hi,
I wanted to give this a try and installed ollama locally. I am able to use the ollama API on http://localhost:11434/api/generate with curl. 
I evaluated `export OLLAMA_API_BASE=http://localhost:11434`, installed holmes using brew as described in the readme and startet
`holmes ask --model ollama/llama3.1:latest  "what issues do I have in my cluster" -v`
resulting in 

APIConnectionError: litellm.APIConnectionError: 'name'
Traceback (most recent call last):
  File "litellm/main.py", line 2422, in completion
  File "litellm/llms/ollama.py", line 293, in get_ollama_response
KeyError: 'name'

![image](https://github.com/user-attachments/assets/3b56e7bd-c1cc-4c46-875d-6c7af98e7363)

Any help how to debug this? Already tryied *-v* which gives no further helpful output. Changed the OLLAMA_API_BASE to http://localhost:11434/ZZ and then receive and 404 as expected, so I assume OLLAMA_API_BASE is working. Also switched to ollama/llama2 model with same result.

Thank you in advance
Max

**Comment by juliendf** [comment]
Also have the same error. Did you find a solution or workaround ?

Thanks

**Comment by arikalon1** [comment]
Hey @juliendf 

I think it's this issue on litellm
https://github.com/BerriAI/litellm/issues/3912#ref-pullrequest-2342067642
https://github.com/ollama/ollama/issues/4398

Which version of Holmes are you using?

**Comment by aantn** [comment]
Hi all, we fixed a number of issues related to this and ollama should work on current holmes versions. If you encounter an issue on the latest version feel free to re-open
